# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format test
version: "{build}"

shallow_clone: true

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

# What combinations to test
environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version x64
  # installing selenium-standalone
  # - npm install -g selenium-standalone
  # - selenium-standalone install
  # opening firewall ports
  # - netsh advfirewall firewall add rule name="SeleniumIn" dir=in action=allow protocol=TCP localport=4444
  # - netsh advfirewall firewall add rule name="SeleniumOut" dir=out action=allow protocol=TCP localport=4444
  # running selenium-standalone as background job
  # - ps: Start-Process selenium-standalone 'start','--','-Djna.nosys=true'
  # installing local requirements
  - yarn
build: off

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - npm test

# scripts to run after tests
on_finish:
# - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit\*.xml))
# - cmd: node afterTest.js
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


matrix:
  fast_finish: true

cache:
  - "%LOCALAPPDATA%\\Yarn"
